name: Auto Label

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  auto_label:
    name: Auto Label
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull Request
        uses: release-drafter/release-drafter/autolabeler@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
